layout_spectrum: 0.8566036
typography_spectrum: 0.6435325
color:
  saturation: 0.7244977
  lightness: 0.3943705
  brandStrength: 0.8614478
  rhythmicContrast: 0.02160998
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Connie
